---
title: "gun violence cross US"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(usmap)
library(ggplot2)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## data clean
```{r}
gun_violence_state_df=
read_csv("data/gun violence/mass shootings(all years).csv") %>% 
  janitor::clean_names() %>% 
  select(-incident_id,-address,-operations) %>%
  separate(incident_date,into=c("day","month","year"),sep="-") %>% 
  group_by(state,year) %>%
  mutate(number_year_killed=sum(number_killed),number_year_injured=sum(number_injured),year=as.numeric(year)) %>% 
  ungroup() %>% 
  filter(year!="17")

```
## according to states,arrange the number of mass shooting in 48 states in an ascending way

```{r}
mass_shooting_state=
  gun_violence_state_df %>% 
  group_by(state) %>%
  count() %>% 
  select(number_mass_shooting=n) %>% 
  arrange(number_mass_shooting)


mass_shooting_state %>% 
  ggplot(aes(x=fct_reorder(state,number_mass_shooting),y=number_mass_shooting)) + geom_bar(stat = "identity", fill = "lightblue", colour = "black",position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust =1))
  

  
  
  
  
gun_violence_state_df %>%
  group_by(year,state) %>% 
  mutate(number_mass_shooting=n()) %>% 
  group_by(year,state,number_mass_shooting) %>% 
  summarise() %>% 
  filter(year=="21")
  
arrange
  
  
  ggplot(aes(x=year,y=number_year_killed,color=state)) + geom_line()
  
  group_by(state,year,number_year_killed,number_year_injured) %>% 
  summarise()
  
  filter(year=="21")
  ggplot(aes(x=year,y=number_killed,color=state)) + geom_line()
```

## number of mass shooting from 2018 - 2020 years

```{r}
  gun_violence_state_df %>% 
    group_by(year) %>% 
    mutate(number_mass_shooting=n()) %>% 
    group_by(year,number_mass_shooting) %>% 
    summarise() ## result is the same as shown in the table of website of GVA(gun violence archive)


ggplot(aes(x=year,y=number_mass_shooting)) + geom_line()
```




## number of people killed  and injured in mass shooting from  Juanary 2018 to 2021 (since 2021 has not ended,so the latest date is 2021.11.9)
```{r}
gun_violence_state_df %>% 
  group_by(year) %>% 
  mutate(year_nation_killed=sum(number_year_killed),year_nation_injured=sum(number_year_injured)) %>% 
  group_by(year,year_nation_killed,year_nation_injured) %>% 
  summarise()
```



```{r}
plot_usmap(include = c("NY")) +
  labs(title = "Western US States",
       subtitle = "These are the states in the Pacific Timezone.")
```

