---
title: "heatmap"
author: "ZiqianHe"
date: "2021/12/6"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(gridExtra)
library(leaflet)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
historic_NYPD_df = read_csv("./NYPD_Shooting_Incident_Data__Historic_.csv") %>%
  separate('OCCUR_DATE', into=c("month","day","year"),sep = "/") %>%
  filter(year>=2018)
year_to_date_df = read_csv("./NYPD_Shooting_Incident_Data__Year_To_Date_.csv")%>%
  separate('OCCUR_DATE', into=c("month","day","year"),sep = "/")
df = bind_rows(historic_NYPD_df,year_to_date_df)
```


```{r}

df_period_before = df %>%
  arrange(year,month,day)%>%
  filter(year <= 2019) %>% 
  separate(OCCUR_TIME,into = c("hour","minute","second"),sep = ":")%>%
  mutate(hour=as.numeric(hour))%>%
  group_by(hour) %>%
  summarise(count=n(),
            time="Pre Covid")

df_period_after = df %>%
  arrange(year,month,day)%>%
  filter(year>= 2020) %>% 
  separate(OCCUR_TIME,into = c("hour","minute","second"),sep = ":")%>%
  mutate(hour=as.numeric(hour)) %>% 
  group_by(hour) %>%
  summarise(count=n(),
            time="During Covid")

df_period =
  bind_rows(df_period_before,df_period_after) %>% 
  plot_ly(
    x = ~ hour, y = ~ time, z = ~ count, type = "heatmap", colors = "YlGn"
  ) %>%
  colorbar(title = "Crimes Number", x = 1.1, y = 0.8) 

layout(df_period, title = "Crime frequency: Pre Covid and During Covid v.s. Hour", xaxis = list(title = "Hour"), yaxis = list(title = "Degree"), width = 850, height = 400)


```

```{r}
data_pre = 
  df %>% 
  janitor::clean_names() %>% 
  arrange(year,month,day)%>%
  filter(year <= 2019) %>%
  rename(long = longitude, lat = latitude) %>% 
  group_by(boro) %>% 
  mutate(crime_number = n(),
         crime_number = as.numeric(crime_number))

pal = colorNumeric(
  palette = "Reds",
  domain = data_pre$crime_number,
  na.color = "white")

data_pre %>% 
  mutate(
    label = str_c("<b>crime number: ", crime_number, "</b><br>location: ", lon_lat , sep = "") ) %>%
  leaflet() %>% 
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(lng = ~long, lat = ~lat, weight = 5, stroke = FALSE, radius = ~sqrt(crime_number)*6, popup = ~ label, color = ~pal(crime_number))%>% 
  addLegend("topright", pal = pal, values = ~crime_number,
    title = "2019-2020 Total Gun Crime",
    opacity = 1
  ) %>% 
   setView(-73.8399986, 40.746739, zoom = 10.5)





```

```{r}
data_during = 
  df %>% 
  janitor::clean_names() %>% 
  arrange(year,month,day)%>%
  filter(year >= 2020) %>%
  rename(long = longitude, lat = latitude) %>% 
  group_by(boro) %>% 
  mutate(crime_number = n(),
         crime_number = as.numeric(crime_number))

pal = colorNumeric(
  palette = "Reds",
  domain = data_pre$crime_number)

data_during %>% 
  mutate(
    label = str_c("<b>crime number: ", crime_number, "</b><br>location: ", lon_lat , sep = "") ) %>%
  leaflet() %>% 
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(lng = ~long, lat = ~lat, weight = 5, stroke = FALSE, radius = ~sqrt(crime_number)*6, popup = ~ label, color = ~pal(crime_number))%>% 
  addLegend("topright", pal = pal, values = ~crime_number,
    title = "2020-2021 Total Gun Crime",
    opacity = 1
  ) %>% 
 setView(-73.8399986, 40.746739, zoom = 10.5)
```

```{r}
unemploy = 
  read_csv("Unemployment.csv") %>% 
  separate(label, into = c("year", "month")) %>% 
  filter(year != "2017")
 
unemploy = dplyr::rename(unemploy, state = series_id)

gun_violence = 
  read_csv("data/year_month_state_massshooting.csv") %>% 
  mutate(year = year + 2000) %>% 
  mutate(year = as.character(year))

new_dataframe = 
  right_join(unemploy, gun_violence, by = c("state" = "state", "year" = "year", "month" = "month")) %>% 
  mutate(period = str_remove(period, "[M]"),
         period = as.numeric(period))

```
