---
title: "Gun Violence in the United States"
output: 
  html_document:
    theme: journal
---

<style type="text/css">

h1.title {
  text-align: center;
}

</style>

&nbsp;
&nbsp;

# Exploring and Analysing gun violence and mass shooting in the U.S. and New York
Jie Liu, Xiaoluo Jiao, Ziqian He, Yu Si, Xinyuan Liu, Tianchuan Gao






<font size = "5">*"2020 is an unusual and turbulent year during which the world has struggled with a pandemic for a long time. Since January 15 2020 in which  the first case of Covid-19 appeared in the United States, the epidemic has lasted 22 months and when it will end still remains uncertain. Under the influence of it, people’s lifestyle, mental health and some economic indicators like GDP, unemployment rate fluctuate dramatically in America."*</font>

</center>



## Project motivation

This project is overall motivated by two gun violence incidents in 2021 in which two Chinese students  were killed brutally. As a team of Chinese, we feel grief-stricken for our compatriots’ death and it motivates us to question and investigate the safety issues of studying in the U.S as an international student. Under this circumstance, our group members are inspired to study gun violence and explore the relationship between gun crime rate and Covid-19 outbreak.

&nbsp;

## Data



&nbsp;

## Method



&nbsp;
&nbsp;