---
title: "NYPD_shooting"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggalt)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data Import

```{r cars}
historic_NYPD_df = read_csv("./NYPD_Shooting_Incident_Data__Historic_.csv") %>%
  separate('OCCUR_DATE', into=c("month","day","year"),sep = "/") %>%
  filter(year>=2018)
year_to_date_df = read_csv("./NYPD_Shooting_Incident_Data__Year_To_Date_.csv")%>%
  separate('OCCUR_DATE', into=c("month","day","year"),sep = "/")
df = bind_rows(historic_NYPD_df,year_to_date_df)
```

## Change through date in month

```{r echo=TRUE}
df_time = df %>%
  group_by(year,month) %>%
  summarise(count=n()) %>%
  unite(month,year,month,sep = "/")
df_time%>%
  ggplot(aes(x=month, y=count,group=1))+ geom_xspline(color="lightblue",size=0.7) + geom_point(color="lightblue",size=2) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust =1)) + 
  labs(x = "Month", y = "Shooting Incidents reported", title = "Shooting Incidents Reported by NYPD From Jan 2018 to Sep 2021") + 
  geom_segment(aes(x = 27, y = 10, xend = 27, yend = 300) ,colour = "red",linetype="dashed") + 
  geom_text(aes(x=27, y= 310, label = "first case of death in NYC " ), colour = "red", vjust = -2, hjust = 0.5, size = 3)  + 
  theme(plot.background = element_rect(colour = "lightblue", size = 3, linetype = 1, 
    fill = "white"), plot.title = element_text(colour = "black", face = "bold", 
    size = 12, vjust = 2.5, hjust = 0.3), plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "inches"),axis.text=element_text(colour="black"))
ggsave("NY_change.png")
```

## Race comparison pie
```{r eval=FALSE, include=FALSE}
df_race_before = df %>%
  arrange(year,month,day)%>%
  slice(1206:2205) %>%
  group_by(VIC_RACE) %>%
  summarise(count=n(),
            ratio=(count/1000)*100,
            time="before")%>%
   arrange(count)
df_race_after = df %>%
  arrange(year,month,day)%>%
  slice(2205:4355) %>%
  group_by(VIC_RACE) %>%
  summarise(count=n(),
            ratio=(count/2151)*100,
            time="after")%>%
  arrange(count)
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
p_before=ggplot(df_race_before,aes(x=1,y=count,fill=VIC_RACE))+geom_bar(width = 1, stat = "identity")+
  coord_polar(theta = "y",start = 0)  + scale_fill_brewer("Blues") + blank_theme +
  theme(axis.text.x=element_blank())+
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5)

```

## Boro comparison
```{r}
df_boro_before = df %>%
  arrange(year,month,day)%>%
  slice(1206:2205) %>%
  group_by(BORO) %>%
  summarise(count=n(),
            ratio=(count/1000)*100,
            time="Before COVID")
df_boro_after = df %>%
  arrange(year,month,day)%>%
  slice(2205:4355) %>%
  group_by(BORO) %>%
  summarise(count=n(),
            ratio=(count/2151)*100,
            time="POST-COVID")
df_boro=bind_rows(df_boro_before,df_boro_after)
df_boro%>%
  ggplot(aes(x=fct_reorder(BORO,count),y=count,fill=time))+geom_bar(stat = "identity",position = "dodge")+ 
  labs(x = "Different Boroughs in NYC", y = "Shooting Incidents reported", title = "Shooting Incidents Reported by NYPD From Five Boros in NYC")
ggsave("NY_boro_comparison.png")

```

## Time Period comparison
```{r}
df_period_before = df %>%
  arrange(year,month,day)%>%
  slice(1206:2205) %>%
  separate(OCCUR_TIME,into = c("hour","minute","second"),sep = ":")%>%
  mutate(hour=as.numeric(hour),
    time_period = case_when(
    hour>=0 & hour<6 ~ "MIDNIGHT",
    hour>=6 & hour<12 ~ "MORNING",
    hour>=12 & hour<18 ~ "AFTERNOON",
    hour>=18 & hour<=23 ~ "EVENING"))%>%
  group_by(time_period) %>%
  summarise(count=n(),
            ratio=count/1000,
            time="before")

df_period_after = df %>%
  arrange(year,month,day)%>%
  slice(2205:4355) %>%
  separate(OCCUR_TIME,into = c("hour","minute","second"),sep = ":")%>%
  mutate(hour=as.numeric(hour),
         time_period = case_when(
           hour>=0 & hour<6 ~ "MIDNIGHT",
           hour>=6 & hour<12 ~ "MORNING",
           hour>=12 & hour<18 ~ "AFTERNOON",
           hour>=18 & hour<=23 ~ "EVENING"))%>%
  group_by(time_period) %>%
  summarise(count=n(),
            ratio=count/2151,
            time="after")
df_period=bind_rows(df_period_before,df_period_after)
df_period%>%
  ggplot(aes(x=fct_reorder(time_period,count),y=count,fill=time))+geom_bar(stat = "identity")+ 
  labs(x = "Different time periods", y = "Shooting Incidents reported", title = "Shooting Incidents Reported by NYPD From different time periods in NYC")
ggsave("NY_time_comparison.png")
```

```{r}
df_boro_time = df %>%
  separate(OCCUR_TIME,into = c("hour","minute","second"),sep = ":")%>%
  mutate(hour=as.numeric(hour),
    time_period = case_when(
    hour>=0 & hour<6 ~ "MIDNIGHT",
           hour>=6 & hour<12 ~ "MORNING",
           hour>=12 & hour<18 ~ "AFTERNOON",
           hour>=18 & hour<=23 ~ "EVENING"))%>%
  group_by(time_period,BORO) %>%
  summarise(count=n(),
            ratio=count/1000)
df_boro_time %>%
  ggplot(aes(x = time_period, y = BORO, fill = count))+ geom_tile() +
  scale_fill_viridis_c(direction = -1)+
  labs(x = "Different time periods", y = "Different Boros", title = "Shooting Incidents Reported Cross-compared with Time Period and Boros")
ggsave("cross_comparison_boro_time.png")
```

